telegram:
  bot:
    token:
    username: SuperNewDDGBot

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
scheduler:
  fixedRate: 120000
  fixedDelay: 10